name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
      with:
        flutter-version: '1.12.x' # you can use 1.12
        channel: 'beta'
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter pub run test
